import type { OverviewSlide } from './overviewSlides';

export const salesforceCpqSlides: OverviewSlide[] = [
  {
    id: 'sfcpq-what-why',
    title: 'What is Salesforce CPQ & how to access it',
    bullets: [
      '☁️ Salesforce is the world\'s leading CRM (Customer Relationship Management) platform — it\'s where our entire sales operation lives: every lead, account, opportunity, contract, and deal record.',
      '🗄️ Think of it as the single source of truth for the business side of monday.com — when a rep asks "why can\'t I close this deal?", the answer is almost always somewhere in Salesforce.',
      '🧩 CPQ = Configure (what products), Price (what they cost), Quote (deal details) — Salesforce\'s native app that automates quoting end to end.',
      '🛡️ It puts guardrails on deals: no unapproved pricing, no retired products, and centralized data for accurate forecasting.',
      '📍 Access it from the CPQ Management tab at the top of every Opportunity page (use Chrome for best performance).',
      '🆕 Three entry options: Create a New Offer, Manage Existing Offers, or Change Currency.',
    ],
  },
  {
    id: 'sfcpq-account-hierarchy',
    title: 'The account hierarchy: Global Company → Company → monday Account',
    bullets: [
      '🌍 Global Company — the top of the hierarchy: the real-world organization worldwide (e.g. "Facebook"). Used to manage the full relationship across regions.',
      '🏢 Company Account (regional / "parent account") — a regional entity under the Global Company (e.g. Facebook EMEA, Facebook NAM). Ownership, contracts, and billing entities hang here.',
      '🖥️ monday Account — an actual monday.com instance (a BB account) under a Company. One Company can have many: different teams, departments, or regions each running their own instance.',
      '👀 See it yourself: open any account in Salesforce → Account Hierarchy shows the full tree.',
    ],
    image: 'https://drive.google.com/thumbnail?id=177DeCfNxX9FeJ3cNo4y05LQ73Bo6OsL5&sz=w1600',
  },
  {
    id: 'sfcpq-opportunities',
    title: 'Opportunities: what they are & the types you\'ll see',
    bullets: [
      '💡 An opportunity is Salesforce\'s record of a potential deal — a client considering adding seats, upgrading their plan, renewing, or buying for the first time. It tracks the account, the players, and the potential value.',
      '🎯 The Opportunity Type drives everything downstream — pricing, available products, contract behavior, and who needs to approve.',
      '🆕 New Business — the first deal on a monday Account. Locks the contract type to "New Contract". The monday Account itself should ideally be created through lead conversion in Salesforce, though it can also be created directly from BigBrain when needed.',
      '➕ Expansion — adding seats or products to an existing account with an active contract (created via the "Create Expansion Opportunity" button). Contract Type is set to Pro-Rated — the addition aligns to the existing contract\'s end date.',
      '    ↳ Cross Sale — a flavor of expansion: selling an additional product to an existing customer (e.g. CRM to a work management account). Also Pro-Rated.',
      '🔁 Flat Renewal — re-closing the existing contract at renewal time; auto-created against the renewal.',
      '📉 Downgrade — reducing seats or tier; auto-filled by the system, not manually created.',
      '🛠️ Service — a service-only deal (implementation, training); exposes only service SKUs, no product licenses.',
    ],
  },
  {
    id: 'sfcpq-reading-an-opp',
    title: 'Reading an opportunity like Business Support: the first 60 seconds',
    bullets: [
      '🧭 Every ticket that mentions a deal starts the same way — open the opp and read five things before touching anything.',
      '1️⃣ **Stage** — is it open, Closed Won, or locked? (Opps lock on the 5th of the month after close.) This decides whether the rep can self-fix or needs a Correction Opportunity.',
      '2️⃣ **Type & Contract Type** — New Business / Expansion / Renewal and New Contract / Pro-Rated. Mismatches here cause the "expansion should have been a renewal" tickets.',
      '3️⃣ **Account Name & Owner** — is the opp on the right monday Account, and is the rep the owner? "Not the account owner" errors and Change Account Owner tickets start here.',
      '4️⃣ **ARR box & Admin section** — Green Bucket ARR, Claimed ARR, and the "Is Recognized" checkbox. Every ARR / claim ticket lives in this corner of the page.',
      '5️⃣ **CPQ Management tab** — the quotes on this opp, their approval status, and which one is Primary. Your entry point for any quote, SO, or approval issue.',
      '💡 Then check the Contract and the BigBrain account. Salesforce shows the deal; BigBrain shows what the customer actually has. Most tickets are a gap between the two.',
    ],
  },
  {
    id: 'sfcpq-inspector',
    title: 'The Inspector: our field-level power tool',
    bullets: [
      '🔍 The Inspector exposes every field on a record — including the ones hidden from the standard layout. It\'s where most Business Support fixes actually happen.',
      '🛠️ Fields you\'ll touch most: **Type** and **Type Auto Filled** (fixing opp type), **Renewal Creation Source**, **Migrate to CPQ Contract**, and the **manager ID fields** (Direct / Second / Third / Fourth Level Manager) on quotes.',
      '🎫 Ticket tie-in: "Expansion closed as Renewal" → Inspector to change Type + Type Auto Filled + Renewal Creation Source. "SO Approval Issues" → Inspector to find the empty manager ID field. "Close Won duplicate key" → Inspector to flip Migrate to CPQ Contract.',
      '⚠️ Rule 1: only edit what the playbook or a teammate confirmed. Inspector edits change live data with no undo.',
      '📝 Rule 2: document every field you changed — old value, new value, why — in the ticket. Future you (and audits) will thank you.',
      '🔒 Rule 3: if the opp is locked, unlock it first — and re-lock or Close Won again when done.',
    ],
  },
  {
    id: 'sfcpq-contracts',
    title: 'Contracts & subscriptions: where the hierarchy bites',
    bullets: [
      '📜 A Contract is created automatically on Close Won and is defined by its end date. Under it hang CPQ Subscriptions — the actual products and seats the customer has.',
      '🏢 The Contract\'s **Account Name must be the Company Account**, not a monday Account. When it isn\'t, reps can\'t create expansion opps — you\'ll see "You cannot create an opportunity for this account because you are not the account owner". Fix: open the Current Contract → change Account Name to the Company.',
      '🔗 Every quote must link to the account\'s **most current contract** — a validation rule blocks submission otherwise. Fix: the rep creates a new quote from scratch via "Create new quote".',
      '🔁 If a rep reopens a Closed Won opp and closes it again, CPQ tries to recreate subscriptions that already exist → "DUPLICATE_VALUE… Uniqe_Key__c". Fix: delete the CPQ Subscriptions on the Contract, or toggle Migrate to CPQ Contract False → True.',
      '📅 One renewal opp per contract year. When a rep closes an expansion that should have been a renewal, fix the opp type, link the Contract to the new renewal opp, and delete the leftover open renewal.',
      '🧭 Reading tip: Contract → Contract Information → Account Name, and Contract → CPQ Subscriptions section. Those two spots resolve most contract tickets.',
    ],
  },
  {
    id: 'sfcpq-quote-to-close',
    title: 'Quote → SO → Closed Won: where it breaks (and what we do)',
    bullets: [
      '🧮 The happy path: quote built in the QLE → submitted → approvals → Sales Order signed in the Deal Room → Closed Won → contract created → activation.',
      '🛑 **"Quote fails to generate / no valid price"** — price book, currency, or required fields (billing country, term, payment terms) don\'t match the account. Check the account\'s currency and tier first; escalate to CPQ Tech with the full error if it persists.',
      '🛑 **"Not linked to current contract"** — validation rule on submission. The rep needs a fresh quote; nothing for us to fix on the old one.',
      '🛑 **Stuck "In Approval Process"** — check Preview Approvals on the CPQ Management tab to see who is pending. Warning: editing a quote in approval recalls it and resets the whole chain.',
      '🛑 **Can\'t change billing entity / signer / company name after close** — that\'s a Correction Opportunity, not an edit (next slides).',
      '💡 Business Support rarely builds quotes — we diagnose why a rep\'s quote won\'t move. Always ask for the quote number and a screenshot of the exact error.',
    ],
  },
  {
    id: 'sfcpq-approvals',
    title: 'Approvals: anatomy of "Unable to find Approver for Rule ID"',
    bullets: [
      '🪜 When a quote is submitted, CPQ walks the discount through approval rules — each rule points at an **Approver Field** on the quote (e.g. Third_Level_Manager__c) that must contain a user ID.',
      '🚨 The error "sbaa.ApprovalTreeProcessor.ApprovalException: Unable to find Approver for Rule ID: a6W…" means one of those fields is empty. The Rule ID tells you which one.',
      '🔎 Step 1: paste the Rule ID into Salesforce search → it opens the Approval Rule → read the Approver Field name.',
      '🔎 Step 2: open the quote → Inspector → find that field. Empty? Go to the rep who owns the Sales Order → walk up their manager chain → copy the right manager\'s user ID → fill it in.',
      '🔁 Step 3: have the rep resubmit. Approvers get email (approve/reject inline) or Slack; pending SOs also live in the "Pending Approvals" tab.',
      '🧑‍💼 Approver out of office? Point them (or their manager) to CPQ Delegation (avatar → CPQ Delegation → delegate + dates). Approval tiers by discount % — **(check with team)** for current thresholds.',
    ],
  },
  {
    id: 'sfcpq-post-won',
    title: 'After Closed Won: locks, Correction Opportunities & the Post-Won Wizard',
    bullets: [
      '🔒 Opportunities lock on the **5th of the month after close** (closed in July → editable until August 5th). After that, no direct edits to the SO.',
      '🩹 A **Correction Opportunity** is a $0-ARR opp used purely to fix invoicing details on a locked deal. Three use cases only: change Billing Entity, change Company Name, change SO Signer.',
      '🧙 The rep starts it from the **Post-Won Wizard** on the opp → picks the correction type → follows the guided steps. Our job is usually to point them there and unblock the edge cases.',
      '💳 Billing Entity changes: loop in Finance Billing — they own "Bill-to" details. If tax info changes, Finance must make the change; otherwise a new Billing Entity can simply be created.',
      '📝 The rep must **clone the quote**, get it re-signed, and upload the signed SO before closing the correction opp. Skipping the clone is the most common mistake.',
      '📊 Corrections carry 0 ARR and never affect attainment — reassure reps who worry about their numbers.',
    ],
  },
  {
    id: 'sfcpq-claims-recognition',
    title: 'Claims & recognition: the ARR corner of the opportunity',
    bullets: [
      '💸 Two payment paths, two claim behaviors. **Wire**: SO signed in CPQ, auto-claimed, activated via Import SO. **Credit Card**: customer pays in-platform; the rep must claim it via "Claim Credit Card Payments" on the opp.',
      '⏳ CC claims are only possible within **6 months of payment** and within the rep\'s **Ownership Claim Eligibility** window. "Not within the account owner claim eligibility timeframe" = the account was created after the purchase. Fix: get proof of contact on/before the claim date → update the eligibility date → link the proof.',
      '💰 **Green Bucket / Is Recognized**: an opp only counts toward a rep\'s target if it clears the recognition threshold — yearly Pro/Enterprise plans, account ARR over $7K ($3.5K for SMB/Product reps).',
      '☑️ When a deal should be recognized but isn\'t: open the opp → **Admin section** → check Is Recognized → fill "Is Recognized – Override Reason" with the ticket link. Never override without a documented ticket.',
      '🏷️ Fields to know: Green_Bucket_ARR_V2__c (the ARR at the top of the opp), Expected_ARR__c (Added ARR), Claimed_ARR__c (Claimed ARR), plus the Recognition Details box on the monday Account.',
      '🚩 Threshold looks wrong for the whole segment, not just one deal? That\'s config — escalate to RevOps with record IDs rather than overriding one by one.',
    ],
  },
  {
    id: 'sfcpq-ownership-access',
    title: 'Ownership & access: the #2 ticket topic',
    bullets: [
      '👤 Account ownership lives in the **Account Owner** field. Accounts with no rep sit in the **Accounts Pool**. AMs and Outbound AEs typically own at the Company level; AEs, Scale AMs, and Partners at the monday Account level.',
      '🎫 "Change Account Owner" (~37 tickets/week) usually arrives as "I can\'t create an opportunity" — the rep isn\'t the owner. Get approval from the current owner + their manager + the RevOps business partner (check the BizLounge routing doc for who).',
      '🔁 Then: Company page → **Change Company Owner** → new rep\'s name → ticket link in the description. The change trickles down to every monday Account under that Company.',
      '🚫 "Insufficient privileges / You do not have access to this record" — a permissions issue, not ownership. Compare the rep\'s role and permission sets to a peer who can see the record; request access via the account owner or add the right permission set.',
      '🔐 Salesforce login failures: confirm production vs sandbox URL, check the user is active in Setup → Users, then SSO/IdP or password reset via IT.',
      '💡 Ownership questions are approval-heavy — set expectations with the rep up front that you\'re waiting on sign-off, not on the fix itself.',
    ],
  },
  {
    id: 'sfcpq-activation-payments',
    title: 'Activation & payment methods: closing the loop in BigBrain',
    bullets: [
      '🚀 Closed Won isn\'t the finish line — the plan must be **activated**. Wire deals activate via **Import SO** in the Close Opportunity flow; Salesforce shows a yellow "Activation Scheduled" banner until it\'s done.',
      '🧠 Verify in BigBrain: the account\'s subscription, seats, tier, and add-ons should match the SO. If they don\'t, that\'s an activation ticket — check Import SO was completed before escalating to Billing Dev.',
      '🧩 Add-ons (Premium Support, Automation Package, AI Credits…) are sold in CPQ but **activate in BigBrain** — confirm under the BB account profile. Add-on-only deals are only allowed as a pro-rated change to an existing contract.',
      '💳➡️🏦 CC → Wire (usually at renewal): a New Contract quote in CPQ; pro-rated is not an option. 🏦➡️💳 Wire → CC: cancel the subscription in BigBrain first, then generate a payment link.',
      '📆 Scheduled activations tied to billing-cycle dates show up as on-hold Add-on Activation tickets — that\'s working as designed, just track the target date.',
    ],
  },
  {
    id: 'sfcpq-triage-cheatsheet',
    title: 'Triage cheat sheet: error → likely cause → first place to look',
    bullets: [
      '🔴 **"You cannot create an opportunity… not the account owner"** → Contract Account Name points at a monday Account, or rep isn\'t the owner → Current Contract → Account Name; then Account Owner.',
      '🔴 **"Unable to find Approver for Rule ID"** → empty manager ID field on the quote → search the Rule ID → Approver Field → quote Inspector.',
      '🔴 **"DUPLICATE_VALUE… Uniqe_Key__c"** → opp reopened and re-closed → Contract → CPQ Subscriptions.',
      '🔴 **"Not within the account owner claim eligibility timeframe"** → account created after the CC purchase → Ownership Claim Eligibility Date on the monday Account.',
      '🟠 **"Is Recognized unchecked / not counting as Added ARR"** → below threshold or excluded plan → opp Admin section + Recognition Details.',
      '🟠 **"Please change expansion to renewal"** → wrong opp type → Inspector (Type, Type Auto Filled, Renewal Creation Source) + Contract link.',
      '🟠 **"I need to change billing entity / signer / company name"** → locked opp → Post-Won Wizard → Correction Opportunity.',
      '🟢 **"Can\'t log in / insufficient privileges"** → access, not data → Setup → Users; permission sets; compare to a peer.',
    ],
  },
];
